#!/usr/bin/env bash
# install nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R $USER:$USER /var/www
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
