#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom heade (on web-01 and web-02)

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
