#!/usr/bin/env bash
# Bash script to configure nginx to listen on port 80
apt install -y nginx
sed -i 's/listen 80/listen 80 default_server/g' /etc/nginx/sites-available/default
service nginx restart
