#!/usr/bin/env bash
# A bash script that displays a list of currently running processes
# Requirements:
# Must show all processes, for all users, including those which migh not have a TTY
# Display in a user-oriented format
# Show process hierarchy
ps aux --forest
