#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

counter=0

# Using a while loop to repeat the statement 10 times
while [ $counter -lt 10 ];
do
    echo "Best School"
    ((counter++))
done
