#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

counter=0

# Using a while loop to repeat the statement 10 times
while [ $counter -lt 10 ]; do
    if [ $counter -eq 8 ]; then
        echo -e "Best School\nHi"
    else
        echo "Best School"
    fi
    ((counter++))
done
