#!/usr/bin/env bash

#displays the time for 12 hours and 59 minutes
#display hours from 0 to 12
#display minutes from 1 to 59

hour=0
while [ $hour -le 12 ]; do
    minutes=1
    while [ $minutes -le 59 ]; do
        printf "%02d:%02d\n" $hour $minutes
        minutes=$((minutes+1))
    done
    hour=$((hour+1))
done | head -n 70
