#!/usr/bin/env bash
# displays the content of the current directory
# display in a list format
# display where only the part of the name after the first dash is displayed

for file in *; do
    # Check if the file is not a hidden file
    if [[ $file != .* ]]; then
        # Extract the part of the name after the first dash
        display_name=$(echo "$file" | cut -d'-' -f2-)
        
        # Display the formatted output
        echo "$display_name"
    fi
done
