#!/usr/bin/env bash
# return a page containing Hello Holberton when querying the root of it

docker exec -it <container_id> /bin/bash

# Navigate to the Apache root directory
cd /var/www/html

# Create an HTML file with the content "Hello Holberton"
echo "Hello Holberton" > index.html

# Restart the Apache service
service apache2 restart

# Exit the container
exit
